name: image_fix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  image_fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker buildx imagetools create --tag grafana/pyroscope:1.5.0 grafana/pyroscope:latest
